
---------- load packages ----------
```{r include=FALSE}
library(tidyverse)
library(ggpubr)
library(nlme)
library(ggrepel)
library(MuMIn)
```


---------- load data, split in O2 data and calcification data & exclude outliers after visual inspection of obs-expected percentages ----------
```{r}
#outlier exclusion in diversity incubations

#O2 measurements
Data <- read.csv("Data/All_expectedvalues.csv")

Day13 <- Data %>% filter(day =="13")
Day13<- Day13 %>% filter(fragment_ID != "SpiB2_AcyD2_PcyC3" )

Day9 <- Data %>% filter(day =="9")
Day9<- Day9 %>% filter(fragment_ID != "PdaA2_AmuD2_PruD3" & fragment_ID != "PveF1_MdiC1_PcyB1")

Day7 <- Data %>% filter(day =="7")
Day7<- Day7 %>% filter(fragment_ID != "PdaB4_AcyD3_PcyC4")

Data_sub <- Data %>% filter(day != "13" & day != "9" & day != "7")

Data <- rbind(Day13, Day9, Day7, Data_sub)

# calcification measurements
Data_calc <- read.csv("Data/All_expectedvalues.csv")

Day7_calc <- Data_calc %>% filter(day =="7")
Day7_calc<- Day7_calc %>%filter(fragment_ID != "PdaD1_AcyA1_PcyA1")

Day13_calc <- Data_calc %>% filter(day =="13")
Day13_calc<- Day13_calc %>%filter(fragment_ID != "PdaD1_AmuA1_PloD1")

Data_sub_calc <- Data_calc %>%  filter(day != "7" & day != "13")

Data_calc <- rbind(Day7_calc, Day13_calc, Data_sub_calc)

# exclude all NA's
Data <- Data %>% drop_na(net_photo_h_surface)
Data_calc <- Data_calc %>%  drop_na(calc_umol_cm2_h)
```


---------- calculate difference between observed/measured and expected values and normalize to % ----------
This is percentage error, which is the difference between an experimental and theoretical value, divided by the theoretical value, multiplied by 100 to give a percent.
```{r}
#((100/ exp)* net_obs) -100, rewritten it is ((net_obs/exp)*100)-100, is the same as ((net_obs/exp)-1)*100

Data$exp_obs_net_photo <- with(Data,  Data$net_photo_h_surface - Data$exp_Net_photo_ug_h_cm2)
Data$exp_obs_net_photo_perc <- with(Data, ((100 / Data$exp_Net_photo_ug_h_cm2) * Data$net_photo_h_surface)-100)
Data$exp_obs_net_photo_perc <- round(Data$exp_obs_net_photo_perc, 6)

Data$exp_obs_gross_photo <- with(Data, Data$gross_photo_h_surface - Data$exp_Gross_photo_ug_h_cm2)
Data$exp_obs_gross_photo_perc <- with(Data, ((100 / Data$exp_Gross_photo_ug_h_cm2) * Data$gross_photo_h_surface)-100)
Data$exp_obs_gross_photo_perc <- round(Data$exp_obs_gross_photo_perc, 6)

Data$exp_obs_respiration <- with(Data, Data$respiration_h_surface - Data$exp_Resp_ug_h_cm2)
Data$exp_obs_respiration_perc <- with(Data, ((100 / Data$exp_Resp_ug_h_cm2) * Data$respiration_h_surface)-100)
Data$exp_obs_respiration_perc <- round(Data$exp_obs_respiration_perc, 6)

Data_calc$exp_obs_calc <- with(Data_calc, Data_calc$calc_umol_cm2_h - Data_calc$exp_Calc_umol_h_cm2)
Data_calc$exp_obs_calc_perc <- with(Data_calc, ((100 / Data_calc$exp_Calc_umol_h_cm2) * Data_calc$calc_umol_cm2_h)-100)
Data_calc$exp_obs_calc_perc <- round(Data_calc$exp_obs_calc_perc, 6)
```


---------- linear regression between measured and expected productivity with colony as random factor ----------
```{r}
# get only diversity incubations
mix <- Data %>%  filter(category == "mix")
mix_calc <- Data_calc %>%  filter(category == "mix")

 # Net
mod_n <- lme(net_photo_h_surface ~ exp_Net_photo_ug_h_cm2, random = ~1|colony, data=mix)

# Res
mod_r <- lme(respiration_h_surface ~ exp_Resp_ug_h_cm2, random = ~1|colony, data=mix)

# Gross
mod_g <- lme(gross_photo_h_surface ~ exp_Gross_photo_ug_h_cm2, random = ~1|colony, data=mix)

# Calc
mod_c <- lme(calc_umol_cm2_h ~ exp_Calc_umol_h_cm2, random = ~1|colony, data=mix_calc)


# test normailty  and homogeneity of variance -> all looks good
hist(resid(mod_n))
shapiro.test(resid(mod_n)) # good 0.77
qqnorm(resid(mod_n))
plot(resid(mod_n)~fitted(mod_n))

hist(resid(mod_r))
shapiro.test(resid(mod_r)) # good 0.64
qqnorm(resid(mod_r))
plot(resid(mod_r)~fitted(mod_r))

hist(resid(mod_g))
shapiro.test(resid(mod_g)) # good 0.24
qqnorm(resid(mod_g))
plot(resid(mod_g)~fitted(mod_g))

hist(resid(mod_c))
shapiro.test(resid(mod_c)) # good 0.62
qqnorm(resid(mod_c))
plot(resid(mod_c)~fitted(mod_c))


# Models output
# This function (r.squaredGLMM)calculates the margil (fixed effects only) and conditional (including both fixed and random effects) R-squared of a multilevel/hierarchical model following  on Nakagawa et al. (2017) -Nakagawa, S., Johnson, P.C.D., Schielzeth, H. (2017) The coefficient of determination R² and intra-class correlation coefficient from generalized linear mixed-effects models revisited and expanded. J. R. Soc. Interface 14: 20170213.-  get pseudo R2  revised statistics based on Nakagawa et al. (2017) paper
# # The conditional R2 is the proportion of total variance explained through both fixed and random effects
# # Marginal R2 provides the variance explained only by fixed effects

summary(mod_n) #-> Intercept p<0.001, exp p=0.008
MuMIn::r.squaredGLMM(mod_n) # R2m: 0.06      R2c: 0.52

summary(mod_r)#-> Intercept p<0.001, exp p=0.036
MuMIn::r.squaredGLMM(mod_r)# R2m: 0.04      R2c: 0.35

summary(mod_g)#-> Intercept p<0.001, exp p<0.001
MuMIn::r.squaredGLMM(mod_g)# R2m: 0.16      R2c: 0.57

summary(mod_c)#-> Intercept p<0.001, exp p<0.001
MuMIn::r.squaredGLMM(mod_c)# R2m: 0.20      R2c: 0.33

```



---------- relationship between productivity change of diverse incubations and their expected productivity ----------
Blomqvist method for x, y-x (stats used in Figure 5 Polyculture productivity link to monoculture performance)
```{r include = FALSE}
################################ Net
mix_net <- mix %>% 
  dplyr::select(fragment_ID, colony, exp_obs_net_photo, net_photo_h_surface, exp_Net_photo_ug_h_cm2) %>% 
  rename(
    base = exp_Net_photo_ug_h_cm2,
    obs = net_photo_h_surface,
    change = exp_obs_net_photo)

# compute inter-colony variance to estimate measurement error
t <- mix_net %>% 
  dplyr::select(colony, fragment_ID, base) %>% 
  full_join(mix_net %>% dplyr::select(colony, fragment_ID, base), by = 'colony') %>% 
  filter(fragment_ID.x < fragment_ID.y) %>% 
  mutate(diff = abs(base.x - base.y))

corr <- cor.test(mix_net$change, mix_net$base, method = "pearson")
original_correlation <- corr$estimate[[1]]
original_correlation

corr_term <- var(t$diff) / var(t$base.x)
corrected_correlation <- (original_correlation + corr_term) / (1 - corr_term)
corrected_correlation


# confidence intervalls based on Fisher z transformation
r.cint <- function(r,n,level=.95) {
 z <- 0.5*log((1+r)/(1-r))
 zse <- 1/sqrt(n-3)
 zmin <- z - zse * qnorm((1-level)/2,lower.tail=FALSE)
 zmax <- z + zse * qnorm((1-level)/2,lower.tail=FALSE)
 return(c((exp(2*zmin)-1)/(exp(2*zmin)+1),(exp(2*zmax)-1)/(exp(2*zmax)+1)))
}

r.cint(corrected_correlation, length(mix$exp_Net_photo_ug_h_cm2))

# p value based on Fisher z transformation
z <- function(r){1/2 * log((1+r)/(1-r))} # Normalverteilung korrigieren nach Fisher
zse <- 1/(sqrt(length(mix$exp_Net_photo_ug_h_cm2)-3))

z_blom <- z(corrected_correlation)

 min(pnorm(z_blom, sd= zse), pnorm(z_blom, lower.tail=FALSE, sd=zse))*2

#Net original: -0.69, corrected: -0.22 Conf 95%(-0.40 to -0.03), p= 0.02
 
 
####################################### Resp
mix_res <- mix %>% 
  dplyr::select(fragment_ID, colony, exp_obs_respiration, respiration_h_surface, exp_Resp_ug_h_cm2) %>% 
  rename(
    base = exp_Resp_ug_h_cm2,
    obs = respiration_h_surface,
    change = exp_obs_respiration)

# compute inter-colony variance to estimate measurement error
t <- mix_res %>% 
  dplyr::select(colony, fragment_ID, base) %>% 
  full_join(mix_res %>% dplyr::select(colony, fragment_ID, base), by = 'colony') %>% 
  filter(fragment_ID.x < fragment_ID.y) %>% 
  mutate(diff = abs(base.x - base.y))

corr <- cor.test(mix_res$change, mix_res$base, method = "pearson")
original_correlation <- corr$estimate[[1]]
original_correlation

corr_term <- var(t$diff) / var(t$base.x)
corrected_correlation <- (original_correlation + corr_term) / (1 - corr_term)
corrected_correlation


# confidence intervalls based on Fisher z transformation
r.cint <- function(r,n,level=.95) {
 z <- 0.5*log((1+r)/(1-r))
 zse <- 1/sqrt(n-3)
 zmin <- z - zse * qnorm((1-level)/2,lower.tail=FALSE)
 zmax <- z + zse * qnorm((1-level)/2,lower.tail=FALSE)
 return(c((exp(2*zmin)-1)/(exp(2*zmin)+1),(exp(2*zmax)-1)/(exp(2*zmax)+1)))
}

r.cint(corrected_correlation, length(mix$exp_Resp_ug_h_cm2))

# p value based on Fisher z transformation
z <- function(r){1/2 * log((1+r)/(1-r))} # Normalverteilung korrigieren nach Fisher
zse <- 1/(sqrt(length(mix$exp_Resp_ug_h_cm2)-3))

z_blom <- z(corrected_correlation)

 min(pnorm(z_blom, sd= zse), pnorm(z_blom, lower.tail=FALSE, sd=zse))*2

 #Resp original: -0.62, corrected: -0.29 Conf 95%(-0.46 to -0.11), p= 0.002 
 
 
 ################################ Gross
mix_gross <- mix %>% 
  dplyr::select(fragment_ID, colony, exp_obs_gross_photo, gross_photo_h_surface, exp_Gross_photo_ug_h_cm2) %>% 
  rename(
    base = exp_Gross_photo_ug_h_cm2,
    obs = gross_photo_h_surface,
    change = exp_obs_gross_photo)

# compute inter-colony variance to estimate measurement error
t <- mix_gross %>% 
  dplyr::select(colony, fragment_ID, base) %>% 
  full_join(mix_gross %>% dplyr::select(colony, fragment_ID, base), by = 'colony') %>% 
  filter(fragment_ID.x < fragment_ID.y) %>% 
  mutate(diff = abs(base.x - base.y))

corr <- cor.test(mix_gross$change, mix_gross$base, method = "pearson")
original_correlation <- corr$estimate[[1]]
original_correlation

corr_term <- var(t$diff) / var(t$base.x)
corrected_correlation <- (original_correlation + corr_term) / (1 - corr_term)
corrected_correlation


# confidence intervalls based on Fisher z transformation
r.cint <- function(r,n,level=.95) {
 z <- 0.5*log((1+r)/(1-r))
 zse <- 1/sqrt(n-3)
 zmin <- z - zse * qnorm((1-level)/2,lower.tail=FALSE)
 zmax <- z + zse * qnorm((1-level)/2,lower.tail=FALSE)
 return(c((exp(2*zmin)-1)/(exp(2*zmin)+1),(exp(2*zmax)-1)/(exp(2*zmax)+1)))
}

r.cint(corrected_correlation, length(mix$exp_Gross_photo_ug_h_cm2))

# p value based on Fisher z transformation
z <- function(r){1/2 * log((1+r)/(1-r))} # Normalverteilung korrigieren nach Fisher
zse <- 1/(sqrt(length(mix$exp_Gross_photo_ug_h_cm2)-3))

z_blom <- z(corrected_correlation)

 min(pnorm(z_blom, sd= zse), pnorm(z_blom, lower.tail=FALSE, sd=zse))*2

#gross original: -0.56, corrected: -0.34 Conf 95%(-0.5 to -0.16), p= 0.0004
 
 
 ################################ Calc
mix_cal <- mix_calc %>% 
  dplyr::select(fragment_ID, colony, exp_obs_calc, calc_umol_cm2_h, exp_Calc_umol_h_cm2) %>% 
  rename(
    base = exp_Calc_umol_h_cm2,
    obs = calc_umol_cm2_h,
    change = exp_obs_calc)

# compute inter-colony variance to estimate measurement error
t <- mix_cal %>% 
  dplyr::select(colony, fragment_ID, base) %>% 
  full_join(mix_cal %>% dplyr::select(colony, fragment_ID, base), by = 'colony') %>% 
  filter(fragment_ID.x < fragment_ID.y) %>% 
  mutate(diff = abs(base.x - base.y))

corr <- cor.test(mix_cal$change, mix_cal$base, method = "pearson")
original_correlation <- corr$estimate[[1]]
original_correlation

corr_term <- var(t$diff) / var(t$base.x)
corrected_correlation <- (original_correlation + corr_term) / (1 - corr_term)
corrected_correlation


# confidence intervalls based on Fisher z transformation
r.cint <- function(r,n,level=.95) {
 z <- 0.5*log((1+r)/(1-r))
 zse <- 1/sqrt(n-3)
 zmin <- z - zse * qnorm((1-level)/2,lower.tail=FALSE)
 zmax <- z + zse * qnorm((1-level)/2,lower.tail=FALSE)
 return(c((exp(2*zmin)-1)/(exp(2*zmin)+1),(exp(2*zmax)-1)/(exp(2*zmax)+1)))
}

r.cint(corrected_correlation, length(mix$exp_Calc_umol_h_cm2))

# p value based on Fisher z transformation
z <- function(r){1/2 * log((1+r)/(1-r))} # Normalverteilung korrigieren nach Fisher
zse <- 1/(sqrt(length(mix$exp_Calc_umol_h_cm2)-3))

z_blom <- z(corrected_correlation)

 min(pnorm(z_blom, sd= zse), pnorm(z_blom, lower.tail=FALSE, sd=zse))*2

#Calc original: -0.44, corrected: 0.02 Conf 95%(-0.18 to 0.21), p= 0.9 -> non sig.
```


---------- Figure 5: Polyculture productivity link to monoculture performance ----------
```{r}
theme <-theme_classic() +
        theme(
        plot.margin = unit(c(1,0.2,0.2,1), "cm"),
        axis.text.x = element_text(size = 16, color = "black"),
        axis.title.x= element_text(size= 16, face ="bold",margin=margin(10,0,0,0), hjust = 0.5),
        axis.text.y = element_text(size = 16, vjust = 0.5, color = "black"),
        axis.title.y =element_text(hjust = 0.5, size=16,face="bold",margin=margin(0,12,0,0)))

# Figure 5 a-c

 net1 <-ggplot(mix, aes( y = net_photo_h_surface, x = exp_Net_photo_ug_h_cm2 )) +
  geom_point(size=2.5) +
  geom_abline(intercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 23.5, y=38.5, label = "conditional R² = 0.52, p = 0.008", size=4, fontface="bold") +
  scale_x_continuous(limits = c(13, 40), breaks = seq(15, 35, by = 10))+
  scale_y_continuous(limits = c(13, 40), breaks = seq(15, 35, by = 10))+
  xlab(expression(bold(atop("Expected net photosynthesis", paste ("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
  ylab(expression(bold(atop("Measured net photosynthesis", paste("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
   theme


resp2 <-ggplot(mix, aes( x = exp_Resp_ug_h_cm2, y = respiration_h_surface)) +
  geom_point(size=2.5) +
  geom_abline(intercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 18.7, y=33.2, label = "conditional R² = 0.35, p = 0.036", size=4, fontface="bold") +
  scale_x_continuous(limits = c(8.5, 34.5), breaks = seq(10, 30, by = 10))+
  scale_y_continuous(limits = c(8.5, 34.5), breaks = seq(10, 30, by = 10))+
  xlab(expression(bold(atop("Expected respiration", paste ("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
  ylab(expression(bold(atop("Measured respiration", paste("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
   theme

gross3 <-ggplot(mix, aes( x =  exp_Gross_photo_ug_h_cm2, y = gross_photo_h_surface)) +
  geom_point(size=2.5) +
  geom_abline(intercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 43, y=67.5, label = "conditional R² = 0.57, p < 0.001", size=4, fontface="bold") + 
  scale_x_continuous(limits = c(26, 69.5), breaks = seq(30,70, by = 10))+
  scale_y_continuous(limits = c(26, 69.5), breaks = seq(30, 70, by = 10))+
  xlab(expression(bold(atop("Expected gross photosynthesis", paste ("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
  ylab(expression(bold(atop("Measured gross photosynthesis", paste("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
   theme

calc4 <-ggplot(mix_calc, aes(x = exp_Calc_umol_h_cm2, y = calc_umol_cm2_h)) +
  geom_point(size=2.5) +
  geom_abline(intercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 0.26, y=1.31, label = "conditional R² = 0.33, p < 0.001", size=4, fontface="bold") +
  scale_x_continuous(limits = c(-0.02, 1.39), breaks = seq(0, 1.2 , by = 0.4))+
  scale_y_continuous(limits = c(-0.02, 1.39), breaks = seq(0, 1.2, by = 0.4))+
  xlab(expression(bold(paste("Expected calcification (μmol CaCO"[3]," cm" ^-2," h" ^-1,")")))) +
  ylab(expression(bold(atop("Measured calcification", paste("(μmol CaCO"[3]," cm" ^-2," h" ^-1,")"))))) +
   theme
```

```{r}
#Figure 5 e-g
# Note: Graph is slightly misleading, because of mathematical coupling of the varaiables x, y-x

b5 <- ggplot(mix, aes(x = exp_Net_photo_ug_h_cm2, y = exp_obs_net_photo)) +
  geom_point(size=2.5) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 19.5, y=20, label = "R = -0.22, p = 0.02", size=4, fontface="bold") +
  xlab(expression(bold(atop("Expected net photosynthesis", paste ("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
   ylab(expression(bold(atop("Change from expected", paste("net photosynthesis (μg O"[2]," cm" ^-2," h" ^-1,")")))))+
  scale_x_continuous(limits = c(13, 40), breaks = seq(15, 40, by = 10))+
  scale_y_continuous(limits = c(-22, 22), breaks = seq(-20, 20, by = 10))+
  theme

b6 <-ggplot(mix, aes(x = exp_Resp_ug_h_cm2, y = exp_obs_respiration)) +
  geom_point(size=2.5) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 15.8, y=20, label = "R = -0.29, p = 0.002", size=4, fontface="bold") +
  xlab(expression(bold(atop("Expected respiration", paste ("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
   ylab(expression(bold(atop("Change from expected", paste("respiration (μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
  scale_x_continuous(limits = c(10, 32), breaks = seq(10, 30, by = 10))+
  scale_y_continuous(limits = c(-22, 22), breaks = seq(-20, 20, by = 10))+
      theme

b7 <-ggplot(mix, aes(x = exp_Gross_photo_ug_h_cm2, y = exp_obs_gross_photo)) +
  geom_point(size=2.5) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 36.6, y=20, label = "R= -0.34, p < 0.001", size=4, fontface="bold") +
  labs(color = "Productivity score\n(\U03A3\ of medians in monoculture)") +
  xlab(expression(bold(atop("Expected gross photosynthesis", paste ("(μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
   ylab(expression(bold(atop("Change from expecte", paste("gross photosynthesis (μg O"[2]," cm" ^-2," h" ^-1,")"))))) +
  scale_x_continuous(limits = c(27, 65), breaks = seq(25, 70, by = 10))+
  scale_y_continuous(limits = c(-22, 22), breaks = seq(-20, 20, by = 10))+
      theme

b8 <-ggplot(mix_calc, aes(x = exp_Calc_umol_h_cm2, y = exp_obs_calc)) +
  geom_point(size=2.5) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  annotate("text", x= 0.15, y=0.9, label = "R = 0.02, p = 0.9", size=4, fontface="bold") +
  xlab(expression(bold(paste("Expected calcification (μmol CaCO"[3]," cm" ^-2," h" ^-1,")")))) +
   ylab(expression(bold(paste("Measured - expected\ncalcification (μmol CaCO"[3]," cm" ^-2," h" ^-1,")")))) +
  scale_x_continuous(limits = c(-0.02,1.3), breaks = seq(0, 1.2, by = 0.4))+
  scale_y_continuous(limits = c(-1, 1), breaks = seq(-1, 1, by = 0.5))+
      theme
```

```{r}
# combine graphs measured vs expected and change from expected vs expected

# all O2
expObs_bruno_med <- ggarrange(
          net1,resp2,gross3,b5, b6, b7,
          labels = c("a)", "b)", "c)", " d)"," e)","  f)"),
          label.x = 0.25,
          label.y = 0.95,
          ncol = 3, nrow=2,
          hjust = -0.5,
          vjust = 0)

ggsave("Graphs/Mix_allO2_expobs_bruno.png", width=14.5, height= 10, limitsize=FALSE, dpi= 700, expObs_bruno_med)

# all Calc
expObs_bruno_med_calc <- ggarrange(
          calc4, b8,
          labels = c("a)", "b)"),
          label.x = 0,
          label.y = 0.95,
          ncol = 2, nrow=1,
          hjust = -0.5,
          vjust = 0)

ggsave("Graphs/Mix_calc_expobs_bruno.png", width=15, height= 10, limitsize=FALSE, dpi= 700, expObs_bruno_med_calc)
```